name: gh-pages deployment

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          npm ci
          npm i -g gh-pages
      - name: Build
        run: npm run build-with-profiling
        env:
          CI: 'false'
      - name: Copy samples.json
        run: |
          cp src/demo/samples.json build/
      - name: push to gh-pages
        run: |
          git config user.email admin@cheminfo.org
          git config user.name "Cheminfo Bot"
          git remote set-url origin "https://cheminfo-bot:${{ secrets.ACCESS_TOKEN }}@github.com/cheminfo/nmrium.git"
          gh-pages -d build --dotfiles
